config/routes.rb
Authlogic::Application.routes.draw do

  resources :articles
  resources :users
  resources :user_sessions
  
  match 'login' => 'user_sessions#new', :as => :login 
  match 'logout' => 'user_sessions#destroy', :as => :logout
  
  

  root :to => "home#index"

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic
  
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  def to_key
    new_record? ? nil : [ self.send(self.class.primary_key) ]
  end 
  
  def persisted?
    false
  end 
   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user
  
  private 
  def current_user_session
    return @current_user_session if defined?(@current_user_session)
    @current_user_session = UserSession.find
  end
  
  def current_user
    return @current_user if defined?(@current_user)
    @current_user = current_user_session && current_user_session.record
  end
  
  protected 
  
  def required_user
    redirect_to :login if !current_user
  end 
  
  def required_no_user
    redirect_to :root if current_user
  end
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # GET /articles
  # GET /articles.xml
  def index
    @articles = Article.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.xml
  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.xml
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.xml
  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to(@article, :notice => 'Article was successfully created.') }
        format.xml  { render :xml => @article, :status => :created, :location => @article }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.xml
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to(@article, :notice => 'Article was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.xml
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to(articles_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :required_user
  def index
    
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  layout 'login'
  before_filter :required_no_user, :only => :new
  
  def index
    redirect_to :login
  end
  
  def new
    @user_session = UserSession.new     
  end 
  
  def create
    @user_session = UserSession.new(params[:user_session])
    if @user_session.save
      flash[:notice] = "Login successfully" 
      redirect_to :root
    else
      render :action => :new  
    end
  end 
  
  def destroy
    @user_session = UserSession.find 
    @user_session.destroy 
    redirect_to :login
  end 
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :find_user,  :except => [:index, :new, :create]
  
  def index
    @users = User.find :all 
  end 
  
  def show
     
  end 
  
  def new
    @user = User.new  
  end
  
  def edit
    redirect_to(users_url) if not @user   
  end 
  
  def update
    if @user.update_attributes(params[:user]) 
      flash[:notice] = "user successfully updated" 
      redirect_to(users_url)
    else
      render :action => 'edit' 
    end 
  end
  
  def destroy
    if @user
      @user.destroy 
      flash[:notice] = "user deleted" 
      redirect_to(users_url)
    else
       flash[:notice] = "user not found"
       redirect_to(users_url)     
    end 
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = "registration successfull"
       redirect_to(users_url)
    else 
      render :action => 'new' 
    end 
  end 
  
  protected 
    def find_user 
      @user = User.find(params[:id])
    end 
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label : title %><br />
    <%= f.text_field : title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<table>
  <tr>
    <th> title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @articles.each do |article| %>
  <tr>
    <td><%= article. title %></td>
    <td><%= link_to 'Show', article %></td>
    <td><%= link_to 'Edit', edit_article_path(article) %></td>
    <td><%= link_to 'Destroy', article, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b> title:</b>
  <%= @article. title %>
</p>


<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/home/index.html.erb
<h4><%= link_to 'Logout', :logout %></h4>
<h1>You Login now</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Authlogic</title>
  <%= stylesheet_link_tag 'scaffold' %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/login.html.erb
<!doctype html> 
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ --> 
<!--[if lt IE 7 ]> <html class="no-js ie6" lang="en"> <![endif]--> 
<!--[if IE 7 ]>    <html class="no-js ie7" lang="en"> <![endif]--> 
<!--[if IE 8 ]>    <html class="no-js ie8" lang="en"> <![endif]--> 
<!--[if (gte IE 9)|!(IE)]><!--> <html class="no-js" lang="en"> <!--<![endif]--> 
<head> 
  <meta charset="utf-8"> 
 
  <title>Login Form</title> 
 
  <!-- All JavaScript at the bottom, except for Modernizr which enables HTML5 elements & feature detects --> 
  <%= stylesheet_link_tag "login" %>
  <%= javascript_include_tag "modernizr-1.7.min" %>
  <%= csrf_meta_tag %>
</head> 

<body> 
  <%= yield %> 
</body> 

</html>

app/views/user_sessions/new.html.erb
  <div id="container"> 
    <header> 
 
      <p>Login Form <p> 
      <% if @user_session.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user_session.errors.count, "error") %> prohibited this Login from being saved:</h2>

          <ul>
          <% @user_session.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>      
    </header> 
 
    	<div id="main" role="main"> 
 
 
                <%= form_for(@user_session) do |f| %>
 
                    <fieldset> 
            
                        <label for="username">Username <span class="ico"><img src="/images/user.png" alt="Username Icon" border="0" /></span></label> 
 
		               		  <%= f.text_field :username, :id =>'username' %>    
 
                       <label for="password">Password <span class="ico"><img src="/images/pass.png" alt="Password Icon" border="0" /></span></label> 
 
	        	            <%= f.password_field :password, :id => 'password' %>    
 
            		</fieldset> 
 
                    <fieldset> 
                    	
                        <span class="password"><a href="#">Forgot Password</a></span> 
 
                    	<button type=submit>>>&nbsp;&nbsp;&nbsp;GO</button> 
 
                    </fieldset> 
 
 
           		<% end %> 
 
 
 
    	</div> 
 
    <footer> 
 
    </footer> 
 
  </div> <!--! end of #container --> 

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>    
  </div>
  
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>    
  </div>
  
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>    
  </div>
  
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>    
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
        
<% end %>

app/views/users/_user.html.erb
<tr>
  <td><%= link_to user.username, user %></td>
  <td><%= user.email %></td> 
  <td> <%= link_to "Edit", edit_user_path(user) %>  <%= link_to "Delete", user, :method => :delete, :confirm => 'Are you sure?' %> </td>
</tr>

app/views/users/edit.html.erb
<p>Edit User</p>
<%= render :partial => "form", :locals => {:user => @user}%>

app/views/users/index.html.erb
 <div id="nav">
   <%= link_to "Register", new_user_path %>
 </div>
<%= flash[:notice] %>
<p> this is index page </p>
<table>
 <tr>
  <td>Username</td>
  <td>Email</td>
  <td>Action</td>
 </tr>
 <%= render @users %>
</table>

app/views/users/new.html.erb
<p> New User </p> 
<%= render :partial => "form", :locals => {:user => @user}%>

app/views/users/show.html.erb
<p> Show User </p>
<p>User name : <%=@user.username %></p>
<p>Email : <%=@user.email %></p>

<p><%= link_to("Edit",edit_user_path(@user)) %></p>
<p><%= link_to("Back",users_path) %> </p>